import type { Metadata } from 'next';
import '../styles/globals.scss';
import { Header } from '@/components/header/header';
import { Sidebar } from '@/components/sidebar/sidebar';

export const metadata: Metadata = {
  title: 'Food-Track',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja'>
      <head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin='anonymous'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap'
          rel='stylesheet'
        />
      </head>
      <body>
        <Header title='Food-Track' />
        <main>
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
